"""Markdown report generation for E-commerce Ops Agent Mini."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any


def generate_markdown_report(
    report_data: dict[str, Any],
    query: str,
    output_path: Path | str,
) -> Path:
    """Generate a structured Markdown ops report and return the saved path."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    anomalies = report_data.get("product_anomalies", [])
    insights = report_data.get("campaign_insights", [])
    tasks = report_data.get("pending_tasks", [])
    suggestions = report_data.get("suggestions", [])
    next_actions = report_data.get("next_actions", [])

    lines = [
        "# E-commerce Ops Agent Report",
        "",
        f"- Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"- Report type: {report_data.get('report_type', 'daily')}",
        "",
        "## 1. Query",
        "",
        query,
        "",
        "## 2. Product Anomalies",
        "",
    ]
    if anomalies:
        lines.append(f"| Product ID | Title | Type | Reason | Suggestion |")
        lines.append("| --- | --- | --- | --- | --- |")
        for a in anomalies:
            lines.append(
                f"| {a.product_id} | {a.title} | {a.anomaly_type} | {a.reason} | {a.suggestion} |"
            )
    else:
        lines.append("No product anomalies detected.")

    lines.extend(["", "## 3. Campaign Insights", ""])
    if insights:
        lines.append("| Campaign ID | Name | ROI | CTR | Spend | Orders | Insight | Suggestion |")
        lines.append("| --- | --- | ---: | ---: | ---: | ---: | --- | --- |")
        for i in insights:
            lines.append(
                f"| {i.campaign_id} | {i.campaign_name} | {i.roi:.2f} | {i.ctr:.4f} | {i.spend:.0f} | {i.orders} | {i.insight} | {i.suggestion} |"
            )
    else:
        lines.append("All campaigns performing within normal range.")

    lines.extend(["", "## 4. Pending Tasks", ""])
    if tasks:
        lines.append("| Task ID | Priority | Status | Deadline | Description |")
        lines.append("| --- | --- | --- | --- | --- |")
        for t in tasks:
            urgency_flag = "⚠️" if t.urgency == "critical" else ""
            lines.append(
                f"| {t.task_id} | {t.priority} | {t.status} {urgency_flag} | {t.deadline} | {t.description} |"
            )
    else:
        lines.append("No pending tasks.")

    lines.extend(["", "## 5. Ops Suggestions", ""])
    for s in suggestions:
        lines.append(f"- {s}")

    lines.extend(["", "## 6. Next Actions", ""])
    for i, action in enumerate(next_actions, start=1):
        lines.append(f"{i}. {action}")

    lines.extend(["", "---", "", "*This report is generated by E-commerce Ops Agent Mini using mock data for demonstration purposes.*"])

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
